name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  lint-typecheck-format:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Prettier check
      - name: Prettier check
        run: npm run format-check

      # 5️⃣ Run ESLint
      - name: ESLint check
        run: npm run lint

      # 6️⃣ Run TypeScript type check
      - name: TypeScript check
        run: npm run typecheck

      # 7️⃣ Run cdk-nag check
      - name: cdk-nag check
        run: npm run cdk-nag
